spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/tmp/batchdb;MODE=ORACLE
#    url: jdbc:h2:mem:batchdb;MODE=ORACLE
    username: sa
    password:
doma:
  dialect: oracle